services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dhanya@123
      MYSQL_DATABASE: shopedge
    ports:
      - "7306:3306"

  backend:
    build: ./backend-spring-boot
    restart: always
    depends_on:
      - mysql
    ports:
      - "5454:3306"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopedge
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Dhanya@123

  frontend:
    build: ./frontend-react
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:9090
